
### Create a new user
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "email": "juanmiguel431@hotmail.com",
    "password": "juanmiguel431",
    "admin": true
}

### Sign In
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email": "juanmiguel431@hotmail.com",
    "password": "juanmiguel431"
}

### Find a particular user with a given id.

GET localhost:3000/users/1
Content-Type: application/json


### Find all users or filer by email.

GET localhost:3000/users?email=juanmiguel431@gmail.com
Content-Type: application/json

###

GET localhost:3000/users?email=juanmiguel431@hotmail.com
Content-Type: application/json


###

GET localhost:3000/users
Content-Type: application/json


###

DELETE localhost:3000/users/5
Content-Type: application/json


###

PATCH http://localhost:3000/users/5
Content-Type: application/json

{
  "password": "55555"
}

### Find me

GET localhost:3000/auth/me
Content-Type: application/json


### Set Color

POST localhost:3000/auth/colors/green
Content-Type: application/json


### Get Color

GET localhost:3000/auth/colors
Content-Type: application/json
